In [2]:
from scipy import optimize

In [101]:
xc, yc = 101, 101

In [102]:
import math

In [103]:
def parabola(X, theta, p, xc, yc):
    x,y = X
    res = ((x-xc)*math.sin(theta)+(y-yc)*math.cos(theta))**2-2*p*((x-xc)*math.cos(theta)-(y-yc)*math.sin(theta))
    return res

In [104]:
import numpy as np

In [105]:
val=np.asarray([0, 0, 0, 0])

In [106]:
x=np.asarray([xc+10,xc-10,xc+5,xc-5])

In [110]:
y=np.asarray([yc+100-1,yc+100-1, yc+25-1,yc+25-1])

In [111]:
param, param_cov = optimize.curve_fit(parabola, (x,y) , val)

In [112]:
param

array([  1.57079633,  -0.5       , 101.        , 100.        ])

In [56]:
import numpy as np
from scipy.optimize import curve_fit

def func(X, a, b, c):
    x,y = X
    return np.log(a) + b*np.log(x) + c*np.log(y)

# some artificially noisy data to fit
x = np.linspace(0.1,1.1,101)
y = np.linspace(1.,2., 101)
a, b, c = 10., 4., 6.
z = func((x,y), a, b, c) * 1 + np.random.random(101) / 100

# initial guesses for a,b,c:
p0 = 8., 2., 7.
print(curve_fit(func, (x,y), z, p0))

(array([10.02394467,  3.99841329,  6.00339373]), array([[ 1.84980253e-03,  9.83944108e-05, -3.05429472e-04],
       [ 9.83944108e-05,  5.34570676e-06, -1.61648158e-05],
       [-3.05429472e-04, -1.61648158e-05,  5.09217982e-05]]))


In [57]:
z

array([-6.9058126 , -6.46151851, -6.0498586 , -5.67372459, -5.31685414,
       -4.98439357, -4.67372569, -4.3786909 , -4.08896214, -3.8147192 ,
       -3.56087781, -3.3137033 , -3.06866558, -2.83865141, -2.61569701,
       -2.39730677, -2.19413259, -1.98765324, -1.79373484, -1.5962426 ,
       -1.41397196, -1.22987215, -1.05410325, -0.88619286, -0.71435321,
       -0.5577467 , -0.38873309, -0.23789927, -0.08321591,  0.0688568 ,
        0.22030626,  0.35795161,  0.50157546,  0.64352064,  0.77684544,
        0.91637854,  1.04695214,  1.17880083,  1.30348145,  1.42696181,
        1.55095124,  1.6787415 ,  1.79832259,  1.91001724,  2.03002995,
        2.15049192,  2.26115086,  2.36683817,  2.48424136,  2.58946944,
        2.70042501,  2.79911077,  2.90327795,  3.0107657 ,  3.11040055,
        3.21435175,  3.31062876,  3.40822033,  3.50740413,  3.60496778,
        3.69900189,  3.79062678,  3.88576624,  3.98386236,  4.06671601,
        4.15676588,  4.25121927,  4.34109784,  4.42869982,  4.51

In [ ]:
def calc_R(p, yc):
    """ calculate the distance of each 2D points from the center (xc, yc) """
    return sqrt((x-xc)**2 + (y-yc)**2)

def f_2(c):
    """ calculate the algebraic distance between the data points and the mean circle centered at c=(xc, yc) """
    Ri = calc_R(*c)
    return Ri - Ri.mean()

center_estimate = x_m, y_m
center_2, ier = optimize.leastsq(f_2, center_estimate)

xc_2, yc_2 = center_2
Ri_2       = calc_R(*center_2)
R_2        = Ri_2.mean()
residu_2   = sum((Ri_2 - R_2)**2)